spring:
  application:
    name: authservice
  datasource: 
      url: jdbc:postgresql://localhost:5433/authDB
      hikari:
          username: postgres
          password: postgres

  jpa:
      hibernate:
          ddl-auto: create
      properties:
          dialect: org.hibernate.dialect.PostgreSQLDialect

    
server:
    port: 8443
    ssl:
      enabled: true
      key-store: classpath:keystore.p12 
      key-store-password: password
      key-store-type: PKCS12

security:
  jwt:
    secret_key: 4eeab38d706831be4b36612ead768ef8182d1dd6f0e14e5dc934652e297fb16a
    access_token_expiration: 36000000 
    refresh_token_expiration: 252000000  
  
logging:
  level:
    org.springdoc: DEBUG      # Отдельная строка для SpringDoc
    org.springframework.web: DEBUG 